#CLK AND RST
set_location_assignment PIN_B8 -to pausa
set_location_assignment PIN_P11 -to fpga_clk
#HEX0
set_location_assignment PIN_C14 -to disp0[0]
set_location_assignment PIN_E15 -to disp0[1]
set_location_assignment PIN_C15 -to disp0[2]
set_location_assignment PIN_C16 -to disp0[3]
set_location_assignment PIN_E16 -to disp0[4]
set_location_assignment PIN_D17 -to disp0[5]
set_location_assignment PIN_C17 -to disp0[6]
set_location_assignment PIN_D15 -to disp0[7]
#HEX1
set_location_assignment PIN_C18 -to disp1[0]
set_location_assignment PIN_D18 -to disp1[1]
set_location_assignment PIN_E18 -to disp1[2]
set_location_assignment PIN_B16 -to disp1[3]
set_location_assignment PIN_A17 -to disp1[4]
set_location_assignment PIN_A18 -to disp1[5]
set_location_assignment PIN_B17 -to disp1[6]
set_location_assignment PIN_A16 -to disp1[7]
#HEX2
set_location_assignment PIN_B20 -to disp2[0]
set_location_assignment PIN_A20 -to disp2[1]
set_location_assignment PIN_B19 -to disp2[2]
set_location_assignment PIN_A21 -to disp2[3]
set_location_assignment PIN_B21 -to disp2[4]
set_location_assignment PIN_C22 -to disp2[5]
set_location_assignment PIN_B22 -to disp2[6]
set_location_assignment PIN_A19 -to disp2[7]
#HEX3
set_location_assignment PIN_F21 -to disp3[0]
set_location_assignment PIN_E22 -to disp3[1]
set_location_assignment PIN_E21 -to disp3[2]
set_location_assignment PIN_C19 -to disp3[3]
set_location_assignment PIN_C20 -to disp3[4]
set_location_assignment PIN_D19 -to disp3[5]
set_location_assignment PIN_E17 -to disp3[6]
set_location_assignment PIN_D22 -to disp3[7]
#HEX4
set_location_assignment PIN_F18 -to disp4[0]
set_location_assignment PIN_E20 -to disp4[1]
set_location_assignment PIN_E19 -to disp4[2]
set_location_assignment PIN_J18 -to disp4[3]
set_location_assignment PIN_H19 -to disp4[4]
set_location_assignment PIN_F19 -to disp4[5]
set_location_assignment PIN_F20 -to disp4[6]
set_location_assignment PIN_F17 -to disp4[7]
#HEX5
set_location_assignment PIN_J20 -to disp5[0]
set_location_assignment PIN_K20 -to disp5[1]
set_location_assignment PIN_L18 -to disp5[2]
set_location_assignment PIN_N18 -to disp5[3]
set_location_assignment PIN_M20 -to disp5[4]
set_location_assignment PIN_N19 -to disp5[5]
set_location_assignment PIN_N20 -to disp5[6]
set_location_assignment PIN_L19 -to disp5[7]