#CLK AND RST
set_location_assignment PIN_B8 -to rst
set_location_assignment PIN_P11 -to fpga_clk
#SWITCHES
set_location_assignment PIN_C10 -to cuenta_maxima[0]
set_location_assignment PIN_C11 -to cuenta_maxima[1]
set_location_assignment PIN_D12 -to cuenta_maxima[2]
set_location_assignment PIN_C12 -to cuenta_maxima[3]
set_location_assignment PIN_A12 -to cuenta_maxima[4]
set_location_assignment PIN_B12 -to cuenta_maxima[5]
set_location_assignment PIN_A13 -to cuenta_maxima[6]
set_location_assignment PIN_A14 -to cuenta_maxima[7]
set_location_assignment PIN_B14 -to cuenta_maxima[8]
set_location_assignment PIN_F15 -to cuenta_maxima[9]
#HEX0
set_location_assignment PIN_C14 -to disp0[0]
set_location_assignment PIN_E15 -to disp0[1]
set_location_assignment PIN_C15 -to disp0[2]
set_location_assignment PIN_C16 -to disp0[3]
set_location_assignment PIN_E16 -to disp0[4]
set_location_assignment PIN_D17 -to disp0[5]
set_location_assignment PIN_C17 -to disp0[6]
set_location_assignment PIN_D15 -to disp0[7]
#HEX1
set_location_assignment PIN_C18 -to disp1[0]
set_location_assignment PIN_D18 -to disp1[1]
set_location_assignment PIN_E18 -to disp1[2]
set_location_assignment PIN_B16 -to disp1[3]
set_location_assignment PIN_A17 -to disp1[4]
set_location_assignment PIN_A18 -to disp1[5]
set_location_assignment PIN_B17 -to disp1[6]
set_location_assignment PIN_A16 -to disp1[7]
#HEX2
set_location_assignment PIN_B20 -to disp2[0]
set_location_assignment PIN_A20 -to disp2[1]
set_location_assignment PIN_B19 -to disp2[2]
set_location_assignment PIN_A21 -to disp2[3]
set_location_assignment PIN_B21 -to disp2[4]
set_location_assignment PIN_C22 -to disp2[5]
set_location_assignment PIN_B22 -to disp2[6]
set_location_assignment PIN_A19 -to disp2[7]
#HEX3
set_location_assignment PIN_F21 -to disp3[0]
set_location_assignment PIN_E22 -to disp3[1]
set_location_assignment PIN_E21 -to disp3[2]
set_location_assignment PIN_C19 -to disp3[3]
set_location_assignment PIN_C20 -to disp3[4]
set_location_assignment PIN_D19 -to disp3[5]
set_location_assignment PIN_E17 -to disp3[6]
set_location_assignment PIN_D22 -to disp3[7]